<a href="https://colab.research.google.com/github/snigdha2808/Gen-AI-/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
array_1d=np.array([1,3,4,5,6,7,8])
print(array_1d[1:5])#slicing


[3 4 5 6]


In [ ]:
print(array_1d[::3]) #skip 3
print(len(array_1d))

[1 5 8]
7


In [ ]:
#2-D array 222

In [ ]:
print(array_1d[:4]+5)# added  to all elements

[ 6  8  9 10]


In [ ]:
array_2d=np.array([[1,3,4],[5,6,7]])
print(array_2d)
print(array_2d.shape)

[[1 3 4]
 [5 6 7]]
(2, 3)


In [ ]:
print(array_2d[-1,-1])
print(array_2d[1,2])

7
7


In [ ]:
print(array_2d[:,1:])#row,column to start :end

[[3 4]
 [6 7]]


In [ ]:
print(array_2d[:,1:2])

[[3]
 [6]]


In [ ]:
array_3d=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(array_3d)
print(array_3d.shape)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(3, 2, 2)


In [ ]:
print(array_3d[:,0,0])

[1 5 9]


In [ ]:
print(array_3d[2,:,:])#silce,ro,colum

[[ 9 10]
 [11 12]]


In [ ]:
#padas dataframe
import pandas as pd

In [ ]:
data_dict= {'Name': ['Sni','gup', 'ta'],
            'age':['20','22','21'],
            'salary': [55000,45000, 40000]}
print(data_dict)
print(pd.DataFrame(data_dict))

{'Name': ['Sni', 'gup', 'ta'], 'age': ['20', '22', '21'], 'salary': [55000, 45000, 40000]}
  Name age  salary
0  Sni  20   55000
1  gup  22   45000
2   ta  21   40000
